#define WINDOW_TITLE "Fight"
#define DEFAULT_WINDOW_WIDTH 1600
#define DEFAULT_WINDOW_HEIGHT 900
#define PERMANENT_STORAGE_SIZE Megabytes(16)
#define SCRATCH_STORAGE_SIZE Megabytes(16)
#define FRAMES_PER_SECOND (60.f)

#define RENDERER_MAX_REQUESTS 4096
#define RENDERER_MAX_FILLED_RECTS 1024
#define RENDERER_MAX_TEXTURES 32768